### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by besarthoxhaj** [besarthoxhaj/play#2]
- [ ] make styles reusable
- [x] make sure looks good on different phone sizes https://github.com/besarthoxhaj/play/issues/3
- [ ] add dynamic data; with reusable components
- [ ] add animations on total won (number going up)
- [ ] add possibly some screenshots test
